### ISSUE TITLE
Feature request: Show scenes by directory to make it easier to tag them

### ISSUE THREAD

**Issue by bikkmakk86** [cooperdk/YAPO-e-plus#11]
There should be people who have already organized their collection using directories so it would make sense to tag all videos with the same tag inside a directory. This feature would require browsing videos by directories.

**Comment by cooperdk** [comment]
There was a folder view on YAPO, but it is not functional, and I have no idea why. It does add stuff to the db.

@bikkmakk86 - If you feel like contributing, I would be happy to invite you to the trello which I just started (easier to plan ahead that way).

**Comment by cooperdk** [comment]
The folder view has been re-introduced.
Be aware that it requires a filter on the right-hand side, or just pressing enter in the search text box before the page is populated.

I hope this is good enough. If not, please re-open and describe your exact needs.
