### ISSUE TITLE
Duplicate function deletes non-duplicates

### ISSUE THREAD

**Issue by Wimi2** [cooperdk/YAPO-e-plus#38]
**Describe the bug**
I think the software is checking duplicates wrong or in a wrong order in certain constellations. When it deletes the files from the drive, there is no other version of this file left.

**To Reproduce**
1. Add for example the whole drive "D:\\" -> done
2. Delete D:\\ from software without cleaning database. 
2.1. Moving some files around.
3. Add Sub-folder of D:\\ instead of whole drive, because more flexible, e.g. "D\\sorted".
4. Run duplicate check

**Expected behavior**
The software recognizes the new added scenes as "duplicates", deleting either the new ones or the old ones, but leaving none in the process, resulting in a data loss.

Recommendation besides looking into the feature again: Safety measure: moving to trash bin instead of deleting them completely.

Here a screenshot of my now empty folder for the lulz. :D

![image](https://user-images.githubusercontent.com/35209086/90652724-ad34f480-e23e-11ea-9892-7c3a37bf7989.png)

**Comment by cooperdk** [comment]
This should now be fixed. Please get the newest development release
