### ISSUE TITLE
Docker pull fails

### ISSUE THREAD

**Issue by jeanpaulrh** [cooperdk/YAPO-e-plus#49]
**Describe the bug**
I can't pull docker image

**To Reproduce**
`docker pull cooperdk/yapo-eplus
Using default tag: latest
Error response from daemon: manifest for cooperdk/yapo-eplus:latest not found: manifest unknown: manifest unknown`

**Expected behavior**
A docker image should be pulled

**Comment by cooperdk** [comment]
Hello,
I will be taking a look at the docker image later.

For now I suggest using a venv in Python as the docker build may be tricky to set up. It will require you to set up the mapping of  network drives manually. Stored data should persist, though.

**Comment by jeanpaulrh** [comment]
I found another docker image o YAPO-e-plus to pull, but I don't know how current it is.
I managed to bind mount video folder and to scan files, but no automatic scene detection was made.
Let me know via github when docker image is ready and I will try it. Not gonna install without docker though.
Thanks.

**Comment by cooperdk** [comment]
Alright,
The docker version might be too old for the automatic scene scanner to be included. I will spend some time one of the following couple of days to fix the building process.

**Comment by jeanpaulrh** [comment]
Thanks!

**Comment by cooperdk** [comment]
Currently, the latest Docker image is about half a year old. Docker Hub suddenly made the auto-update a paid feature, but I have worked very little on YAPO since then anyway.

A new version will be uploaded in the near future.
