### ISSUE TITLE
[Feature Request] Open Folder also selects the file in explorer

### ISSUE THREAD

**Issue by TedlyTheTalker** [cooperdk/YAPO-e-plus#54]
I use a fairly flat folder structure for a large collection of movies. Opening a scene straight from YAPO in VLC is functional, but I prefer the freedom to chose other players that are already available in Explorer’s Context Menu. The Open Folder button in the scene opens the flat folder, and then I have to manually find the file. I don’t use the rename feature, but I imagine if I did, I may also even have a hard time finding the file.

It would be preferable to bring the file for the referenced scene to focus. Chrome’s “View in folder” feature for downloaded files is a great example. The folder is opened in explorer and the file is pre-selected, which brings it into view even in a folder with a lot of files.

**Comment by cooperdk** [comment]
This is indeed possible (it will open a new File Explorer instance), and will be added in the next update since it's an easy improvement.

**Comment by cooperdk** [comment]
This is now implement for the coming version. Be aware that Explorer might "lose" the file if it takes too long to open the directory.
