### ISSUE TITLE
Feature request: ability to add empornium URL to a scene which automatically imports tags from the site

### ISSUE THREAD

**Issue by bikkmakk86** [cooperdk/YAPO-e-plus#8]
I'm not sure if emp has any actual API for this, but it would make things easier if tags and maybe the cover picture could be imported automatically using the torrent ID

**Comment by derberherbert** [comment]
The id and tags are actually in the .torrent files. No need to scrape the website. The torrent_parser python library can read the information.

Example:
```
import torrent_parser

data = torrent_parser.parse_torrent_file('xxx.torrent')
print(data['comment']) #emp url
print(data['metadata']['title'])
print(data['metadata']['taglist'])
print(data['metadata']['cover url'])
print(data['metadata']['description']) #the actual description text from the website

```

**Comment by bikkmakk86** [comment]
That sounds very promising, however a direct link might be preferred as it could update new tags added since the torrent file was originally downloaded

**Comment by cooperdk** [comment]
This sounds interesting.
However, I don't have access to Empornium, because I haven't been using it enough (???) I am told that my user has been disabled due to inactivity.

So, I need an invite to work with this.

**Comment by bikkmakk86** [comment]
@cooperdk if you've already had an account with them, you should ask them to restore that one or else your new account and your invitor's might get banned:

```
You are allowed 1 account per person per lifetime. If we find you have more than one account, all will be disabled. If you previously had an account, come to our IRC chat to restore it. Connect to irc.digitalirc.org and join #empornium-help or you can use the Webchat.
```

Here's the link to their [webchat](http://anonym.es/?https://webchat.digitalirc.org/), they're usually very easy going people so there shouldn't be a problem with this.

Also I've scrubbed through their rules and even though there doesn't seem to be a rule against scrubbing I think asking them a permission before would be a good idea.

**Comment by bikkmakk86** [comment]
So I've asked and it turns out any scraping is against the rules however as @derberherbert mentioned it is [possible](https://www.empornium.me/forum/thread/106300) to get data from the torrent files itself

**Comment by cooperdk** [comment]
Yeah, but how to get a hold of them, and if you search or download them from EMP, then you technically scrape.

 

Rarbg only includes filenames and filesize.

 

Fra: bikkmakk86 [mailto:notifications@github.com] 
Sendt: 14. juni 2020 15:03
Til: cooperdk/YAPO-e-plus
Cc: cooperdk; Mention
Emne: Re: [cooperdk/YAPO-e-plus] Feature request: ability to add empornium URL to a scene which automatically imports tags from the site (#8)

 

So I've asked and it turns out any scraping is against the rules however as @derberherbert <https://github.com/derberherbert>  mentioned it is possible <https://www.empornium.me/forum/thread/106300>  to get data from the torrent files itself

**Comment by cooperdk** [comment]
I have now contacted the admins by IRC and it seems they cannot find my old account information.
Meaning I apparently don't have an account...

So I do need an invite :-)

**Comment by Merodac** [comment]
i would really advise to leave any link to clearly illegal sites alone.
it is one thing to manage your own, legally owned collection, but linking it to empornium (in ANY way) is just a step further into getting banned or else.

this said - can i get an invite, too? ;-)

**Comment by cooperdk** [comment]
I am actually contemplating on using some scrape functionality from PhoenixAdult.bundle which looks interesting. It has lots of scrapers for video, directly working on the network sites.

 

Fra: Merodac [mailto:notifications@github.com] 
Sendt: 19. juni 2020 14:31
Til: cooperdk/YAPO-e-plus
Cc: cooperdk; Mention
Emne: Re: [cooperdk/YAPO-e-plus] Feature request: ability to add empornium URL to a scene which automatically imports tags from the site (#8)

 

i would really advise to leave any link to clearly illegal sites alone.
it is one thing to manage your own, legally owned collection, but linking it to empornium (in ANY way) is just a step further into getting banned or else.

this said - can i get an invite, too? ;-)

**Comment by cooperdk** [comment]
We are not going to develop YAPO for closed sites like EMP (since we have no way to use it), and we are not going to develop YAPO to support obviously illegal sites.
