### ISSUE TITLE
Docker - Cannot find web browser

### ISSUE THREAD

**Issue by jason4bury** [cooperdk/YAPO-e-plus#92]
Is there any way to stop the automatic opening of a web browser when using docker?

When run, the following error appears and the container exits-

yapo             | Traceback (most recent call last):
yapo             |   File "./yapo.py", line 74, in <module>
yapo             |     startup.startup_sequence()
yapo             |   File "/YAPO/videos/startup.py", line 284, in startup_sequence
yapo             |     webbrowser.get().open_new_tab(site)
yapo             |   File "/usr/local/lib/python3.8/webbrowser.py", line 65, in get
yapo             |     raise Error("could not locate runnable browser")
yapo             | webbrowser.Error: could not locate runnable browser

**Comment by cooperdk** [comment]
Oh yes - sorry. I didn't consider that on Docker, opening the browser should be disabled, or rather, I should disable opening the browser as the default setting.

What you do is find the settings.yml file within your config directory, it should be where you store your Docker data.

And then remove the value of the URL key, so it becomes:

`  yapo_url:`
(remember the required two spaces before the key)

When you open YAPO afterwards, it will know that you don't want any browser opened. That is determined by the presence of a URL as a value to that key.

When you're there, you can insert another key (if not there) named tpdb_apikey - and as value, give your metadataapi.net API key, if you want to use the API scanner feature.

**Comment by jason4bury** [comment]
Thanks for the info,

I tried the fix but I'm afraid it hasn't worked.

When I run the container the error message still appears and the container stops.
