### ISSUE TITLE
Videos in Subfolders

### ISSUE THREAD

**Issue by truefriend-cz** [cooperdk/YAPO-e-plus#99]
Please add function for scan not only videos in one folder but search all videos with subfolders in selected folders.

**Comment by Team-YAPO** [comment]
Hello,

YAPO already recursively traverses the directory input as a source folder. It will include any video files it recognizes out of the box.

If you have any issues regarding this, please log a descriptive bug with details about your file types etc.

**Comment by truefriend-cz** [comment]
This is network share in format:
`\\server\videos1`

**Comment by truefriend-cz** [comment]
Support, do you can fix this? Problem stayed
